// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACEXEKc6Ut0YphFhLkBE6Qibb58D5heHc',
    appId: '1:368061195636:web:1b11e78bd5c38eb1fdf821',
    messagingSenderId: '368061195636',
    projectId: 'kiemphieu-e30c8',
    authDomain: 'kiemphieu-e30c8.firebaseapp.com',
    storageBucket: 'kiemphieu-e30c8.firebasestorage.app',
    measurementId: 'G-WP4BXFKMCC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg7aAeHnmWHV4Mwl1E2r-5aQdY8-WVClg',
    appId: '1:368061195636:ios:80ad3c08f87ebe63fdf821',
    messagingSenderId: '368061195636',
    projectId: 'kiemphieu-e30c8',
    storageBucket: 'kiemphieu-e30c8.firebasestorage.app',
    iosBundleId: 'com.example.kiemphieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg7aAeHnmWHV4Mwl1E2r-5aQdY8-WVClg',
    appId: '1:368061195636:ios:80ad3c08f87ebe63fdf821',
    messagingSenderId: '368061195636',
    projectId: 'kiemphieu-e30c8',
    storageBucket: 'kiemphieu-e30c8.firebasestorage.app',
    iosBundleId: 'com.example.kiemphieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACEXEKc6Ut0YphFhLkBE6Qibb58D5heHc',
    appId: '1:368061195636:web:4c9864e20f4dd82afdf821',
    messagingSenderId: '368061195636',
    projectId: 'kiemphieu-e30c8',
    authDomain: 'kiemphieu-e30c8.firebaseapp.com',
    storageBucket: 'kiemphieu-e30c8.firebasestorage.app',
    measurementId: 'G-03WBHFTEQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSgg-wrxXiS2pCyO0eLptJV_wghcP6s2I',
    appId: '1:368061195636:android:94978648dcc34caafdf821',
    messagingSenderId: '368061195636',
    projectId: 'kiemphieu-e30c8',
    storageBucket: 'kiemphieu-e30c8.appspot.com',
  );

}